name: Compile

on:
  push:
    paths:
      - '*.c'
      - '*.h'
      - '.github/workflows/compile.yml'
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binder.h
        run: curl -O https://raw.githubusercontent.com/torvalds/linux/master/include/uapi/linux/android/binder.h

      - name: Compile
        run: |
          for arch in aarch64 armv7a i686 x86_64; do
              if [ "$arch" == "armv7a" ]; then
                  eabi="eabi"
              else
                  eabi=""
              fi
              $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/${arch}-linux-android${eabi}29-clang 2020-0423.c -o 2020-0423-${arch} -g -pthread
          done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: CVE-2020-0423
          path: ./2020-0423-*
